name: Deploy Next.js site to Pages

on:
  push:
    branches: ['test-gh-pages-static']
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build:
    name: Build Next.js Blog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0' # Update to a supported Node.js version
      - name: Install dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-build
          path: .next

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: nextjs-build
          path: .next
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .next
          publish_branch: gh-pages # or the branch you want to deploy to
